language: node_js
node_js:
  - 10.4.1
sudo: true

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - cd client
  - npm install -g @angular/cli
  - npm install

script:
  - npm run test:ci
  - npm run lint