language: node_js

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

dist: xenial

node_js:
  - stable
python:
  - 3.7

sudo: true

cache:
  pip: true
  npm: true


before_install:
  - pip install --user --upgrade pip
  - pip install --user awscli

branches:
  only:
    - master

before_script:
  - cd client
  - npm install -g @angular/cli
  - npm install

script:
  - npm run build:prod

deploy:
  on:
    branch: master
  provider: s3

  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY

  bucket: oppositereaction.rocks

  skip_cleanup: true

  local_dir: dist

  cache_control: "max-age=21600"

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

jobs:
  include:
    - stage: build_front
      language: node_js
      node_js:
        - stable
      sudo: true
      cache: npm
      branches:
        only:
          - master
      before_script:
        - cd client
        - npm install -g @angular/cli
        - npm install

    - stage: deploy
      script: ./deploy