language: node_js

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

dist: xenial

node_js:
  - 8.16.0
python:
  - 3.7

sudo: true

cache:
  pip: true
  npm: true

matrix:
  fast_finish: true
  include:
    - name: build front
      before_install:
        - pip install --user --upgrade pip
        - pip install --user awscli
      before_script:
        - cd client
        - npm install -g @angular/cli
        - npm install
      script:
        - npm run build:prod
      deploy:
        on:
          branch: master
        provider: s3
        region: $DEPLOY_REGION
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: $BUCKET_NAME
        skip_cleanup: true
        local_dir: dist/oppositeReaction
        cache_control: "max-age=21600"
      after_deploy:
        - aws configure set preview.cloudfront true
        - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
    - name: build server
      before_install:
        - pip install --user --upgrade pip
        - pip install --user awscli
      before_script:
        - cd server
        - npm install
      script:
        - npm run build
      deploy:
        provider: script
        script: chmod +x deployScripts/deploy.prod.sh && deployScripts/deploy.prod.sh
        local_dir: dist
        skip_cleanup: true
        on:
          branch: master
      after_deploy:
        - aws ecs update-service --cluster opposite-cluster --service opposite-service --region eu-north-1 --force-new-deployment



