version: '2'
services:

  express:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - './server/src:/usr/src/app/src'
    ports:
     - "3000:3000"


