version: '2'
services:

  express:
    build: server
    volumes:
      - './server/:/usr/src/app/'
    ports:
     - "3000:3000"
    links:
     - database

  database:
    image: mongo
    ports:
     - "27017:27017"

  dbadmin:
    image: mrvautin/adminmongo
    ports:
      - "1234:1234"
